#Text configuration
signs:
  #Comprobar en que linea escribe
  line: 0
  #Texto que será para subir
  up: "&2[Up]"
  #Texto que será para bajar
  down: "&2[Down]"


#Mensajes Config
messages:
  sign-create: "&8[&4Alert&8]&r &7Creaste un Elevador!"
  teleport-up: "&8[&4Alert&8]&r &7Haz subido!"
  teleport-down: "&8[&4Alert&8]&r &7Haz Bajado!"
  no-safe: "&8[&4Alert&8]&r &7No puedes utilizar el elevador, no es un lugar seguro!"
  no-destination: "&8[&4Alert&8]&r &7No ha establecido a donde subir/bajar!"
