<?php

namespace History\entities;


use pocketmine\entity\Entity;
use pocketmine\level\Level;
use pocketmine\nbt\tag\CompoundTag;

class UtilsEntity extends Entity {

    public function __construct(Level $level, CompoundTag $nbt) {
        parent::__construct($level, $nbt);
    }

    public static function createEntity($type, Level $level, CompoundTag $nbt, ...$args): ?Entity {
        return parent::createEntity($type, $level, $nbt, $args); // TODO: Change the autogenerated stub
    }
}